baseURL: ""
languageCode: en-us
title: XanderGrab
theme: Portfolio-PaperMod-theme

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    defaultTheme: dark

    profileMode:
        enabled: true
        title: üëã Hello there! I'm Xander
        subtitle: "(aka XanderGrab) I'm a Game Developer and Designer as well as an all-around Games Hobbyist. I'm passionate about creating Serious or Applied games."
        imageUrls:
            ["assets/icons/ProfessionalPhoto.JPG", "assets/icons/FancyIcon.png"]
        imageTitle: "My Icon"
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size
        buttons:
            - name: About Me
              url: whoami

    socialIcons:
        - name: github
          url: "https://github.com/XanGrab"

        - name: linkedin
          url: "https://www.linkedin.com/in/alexander-xander-grabowski-8164481a1/"

        - name: itchio
          url: "https://xanxg.itch.io/"

        - name: email
          url: /contact/

    mainSections:
        - games
        - blog

    assets:
        favicon: "assets/favicon/favicon.ico"
        favicon16x16: "assets/favicon/favicon-16x16.png"
        favicon32x32: "assets/favicon/favicon-32x32.png"
        apple_touch_icon: "assets/favicon/apple-touch-icon.png"

menu:
    main:
        - identifier: Resume
          name: "üìú CV"
          url: /assets/docs/grabowski_cv.pdf
          weight: 5
        - identifier: Contact
          name: "‚úâÔ∏è Contact"
          url: /contact/
          weight: 4
        # - identifier: Blog
        #   name: Blog
        #   url: /blog/
        #   weight: 3
        - identifier: Games
          name: "üïπ Games"
          url: /games/
          weight: 2
        - identifier: Search
          name: "üîçÔ∏è Search"
          url: /search/
          weight: 1
